import { Project, TeamMember } from './types';

export const INITIAL_TEAM: TeamMember[] = [
  {
    id: 'm1',
    name: 'Sofía Alcántara',
    email: 'sofia@empresa.com',
    role: 'Product Manager',
    initials: 'SA',
    color: 'bg-emerald-500 text-white',
  },
  {
    id: 'm2',
    name: 'Mateo Russo',
    email: 'mateo@empresa.com',
    role: 'Senior Fullstack Dev',
    initials: 'MR',
    color: 'bg-blue-500 text-white',
  },
  {
    id: 'm3',
    name: 'Clara Méndez',
    email: 'clara@empresa.com',
    role: 'Diseñadora UI/UX',
    initials: 'CM',
    color: 'bg-pink-500 text-white',
  },
  {
    id: 'm4',
    name: 'Andrés Valenzuela',
    email: 'andres@empresa.com',
    role: 'DevOps Engineer',
    initials: 'AV',
    color: 'bg-amber-500 text-white',
  },
  {
    id: 'm5',
    name: 'Laura Torres',
    email: 'laura@empresa.com',
    role: 'Especialista SEO/SEM',
    initials: 'LT',
    color: 'bg-purple-500 text-white',
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'Rediseño E-commerce 2026',
    description: 'Renovación completa de la experiencia de compra, optimización del checkout móvil y migración a React 19 con un diseño ultraligero y de alta velocidad de carga.',
    status: 'active',
    priority: 'high',
    category: 'Desarrollo Web',
    budget: 45000,
    spent: 28000,
    startDate: '2026-05-10',
    dueDate: '2026-08-15',
    progress: 68,
    team: ['m1', 'm2', 'm3'],
    classroom: '2HCA',
    tasks: [
      { id: 't1_1', title: 'Diseño de wireframes de baja fidelidad', completed: true },
      { id: 't1_2', title: 'Aprobación de prototipo de checkout', completed: true },
      { id: 't1_3', title: 'Implementación del catálogo de productos rápido', completed: true },
      { id: 't1_4', title: 'Integración de pasarela de pago segura', completed: false },
      { id: 't1_5', title: 'Pruebas de carga en servidores de staging', completed: false },
    ],
    lastUpdated: '2026-06-28T18:30:00Z',
  },
  {
    id: 'p2',
    name: 'App Móvil - Club de Clientes',
    description: 'Desarrollo de aplicación nativa para iOS y Android que permite acumular puntos, recibir cupones dinámicos de fidelización y escanear tickets en tienda física.',
    status: 'active',
    priority: 'medium',
    category: 'App Móvil',
    budget: 62000,
    spent: 15000,
    startDate: '2026-06-01',
    dueDate: '2026-10-30',
    progress: 25,
    team: ['m2', 'm3', 'm4'],
    classroom: '2HCA',
    tasks: [
      { id: 't2_1', title: 'Definición de arquitectura y API Gateway', completed: true },
      { id: 't2_2', title: 'Diseño de la interfaz de usuario en Figma', completed: false },
      { id: 't2_3', title: 'Integración con SDK de escaneo QR', completed: false },
      { id: 't2_4', title: 'Configuración de pipelines automatizados de CI/CD', completed: false },
    ],
    lastUpdated: '2026-06-25T11:20:00Z',
  },
  {
    id: 'p3',
    name: 'Campaña SEO & Branding Orgánico',
    description: 'Auditoría integral del sitio web, optimización de velocidad Core Web Vitals, estructuración de contenido de blog y creación de enlaces de alta autoridad.',
    status: 'planning',
    priority: 'low',
    category: 'Marketing Digital',
    budget: 12000,
    spent: 1200,
    startDate: '2026-07-01',
    dueDate: '2026-09-01',
    progress: 10,
    team: ['m1', 'm5'],
    classroom: '2HCB',
    tasks: [
      { id: 't3_1', title: 'Análisis de palabras clave de competencia', completed: true },
      { id: 't3_2', title: 'Optimización técnica preliminar (sitemap, robots)', completed: false },
      { id: 't3_3', title: 'Redacción de primeros 5 posts optimizados', completed: false },
    ],
    lastUpdated: '2026-06-29T09:15:00Z',
  },
  {
    id: 'p4',
    name: 'Migración Multi-Cloud Segura',
    description: 'Migración planificada de bases de datos locales a infraestructura escalable basada en la nube, implementando altos estándares de cifrado y backups distribuidos.',
    status: 'completed',
    priority: 'high',
    category: 'Infraestructura',
    budget: 35000,
    spent: 34500,
    startDate: '2026-03-01',
    dueDate: '2026-06-20',
    progress: 100,
    team: ['m4', 'm2'],
    classroom: '2HCB',
    tasks: [
      { id: 't4_1', title: 'Estudio de topología de red y costos', completed: true },
      { id: 't4_2', title: 'Migración en paralelo del entorno de staging', completed: true },
      { id: 't4_3', title: 'Sincronización final de bases de datos en caliente', completed: true },
      { id: 't4_4', title: 'Pruebas de contingencia de recuperación de desastres', completed: true },
    ],
    lastUpdated: '2026-06-20T22:00:00Z',
  },
  {
    id: 'p5',
    name: 'Automatización de Facturas y ERP',
    description: 'Desarrollo de un microservicio de sincronización que conecta la pasarela de pagos con el sistema contable interno, emitiendo facturas en PDF de forma automática.',
    status: 'on_hold',
    priority: 'medium',
    category: 'Sistemas Internos',
    budget: 18000,
    spent: 8500,
    startDate: '2026-04-15',
    dueDate: '2026-07-15',
    progress: 47,
    team: ['m1', 'm2', 'm4'],
    tasks: [
      { id: 't5_1', title: 'Definición de mapeo de campos tributarios', completed: true },
      { id: 't5_2', title: 'Generación de plantilla de factura PDF interactiva', completed: true },
      { id: 't5_3', title: 'Pruebas con sandbox fiscal tributario', completed: false },
    ],
    lastUpdated: '2026-06-12T14:45:00Z',
  }
];

export const AVAILABLE_CATEGORIES = [
  'Desarrollo Web',
  'App Móvil',
  'Marketing Digital',
  'Infraestructura',
  'Sistemas Internos',
  'Diseño de Producto'
];
